source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'ZZXibView_Example', :exclusive => true do
  pod 'ZZXibView', :path => '../'
end

target 'ZZXibView_Tests', :exclusive => true do
  pod 'ZZXibView', :path => '../'

  
end
